### ISSUE TITLE
Redesign

### ISSUE THREAD

**Issue by connorjclark** [Hoten/Java-Delaunay#1]
Get a full understanding of the program. Design and implement from scratch, not a 1:1 rewrite. Employ automatic testing. I want to brush up on Groovy, so use that. See if there are any libraries to cut down on the work involved.

**Comment by connorjclark** [comment]
Lloyd relaxation with variable distance metrics would be interesting (https://en.wikipedia.org/wiki/Lloyd%27s_algorithm#Different_distances)

**Comment by connorjclark** [comment]
A rename is in order as well. Perhaps 'mappy'?

**Comment by jacksondus** [comment]
Seems dead, but Jelaunay seems good to me.

**Comment by connorjclark** [comment]
Not dead, a long slumber.

**Comment by SomeFire** [comment]
Toooooo long)

**Comment by connorjclark** [comment]
k this is dead.

I may remake this in js for https://github.com/connorjclark/gridia-2019-wip
